# Generated by Django 5.2.5 on 2025-08-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatereferral',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Commission Paid'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
    ]
