# Generated by Django 5.2.5 on 2025-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_affiliateprofile_paid_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateprofile',
            name='affiliate_code',
            field=models.CharField(blank=True, help_text='Unique referral code (6-12 characters, letters and numbers only). Required for approval.', max_length=20, null=True, unique=True),
        ),
    ]
