# Generated by Django 5.2.5 on 2025-08-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_alter_affiliatereferral_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepayment',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliatereferral',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
    ]
