# Generated by Django 5.2.5 on 2025-09-02 11:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_update_affiliate_code_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateprofile',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='affiliate_documents/aadhar/'),
        ),
        migrations.AlterField(
            model_name='affiliateprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='affiliate_documents/pan/'),
        ),
    ]
