# Generated by Django 5.2.5 on 2025-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
