# Generated by Django 5.2 on 2025-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='gst_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='kyc_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('not_submitted', 'Not Submitted')], default='not_submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
