# Generated by Django 5.2.5 on 2025-11-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_change_business_default_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for business introduction (e.g., https://youtube.com/watch?v=abc123)', null=True),
        ),
    ]
