# Generated by Django 5.2 on 2025-06-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_review_email_review_name_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('coupon_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_requests', to='directory.business')),
            ],
        ),
    ]
