# Generated by Django 5.2.4 on 2025-07-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_couponrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
