# Generated by Django 5.2.5 on 2025-08-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_business_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='gst_document',
            field=models.FileField(blank=True, null=True, upload_to='gst_documents/'),
        ),
    ]
