# Generated by Django 5.2.5 on 2025-08-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='directory.business'),
        ),
    ]
