# Generated by Django 5.2.5 on 2025-08-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_usersubscription_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='directory.subscriptionplan'),
        ),
    ]
