# Generated by Django 5.2.5 on 2025-08-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_business_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
