# Generated by Django 5.2.5 on 2025-09-03 10:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_usersubscription_affiliate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='gst_document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='gst_documents/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_document',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='business_images/'),
        ),
    ]
