# Generated by Django 5.2.5 on 2025-09-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_alter_business_gst_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='formatted_address',
            field=models.TextField(blank=True, help_text='Google formatted address'),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='location_name',
            field=models.CharField(default='', help_text='Google Places location name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Places ID', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(help_text='Full formatted address from Google'),
        ),
    ]
