# Generated by Django 5.2.5 on 2025-09-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_business_district_business_formatted_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='formatted_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
