# Generated by Django 5.2.5 on 2025-09-21 08:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_remove_district_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='payment_screenshots/'),
        ),
    ]
