# Generated by Django 5.2.5 on 2025-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_update_payment_screenshot_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
