# Generated by Django 5.2.5 on 2025-10-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_alter_business_address_alter_business_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='city',
        ),
    ]
