# Generated by Django 5.2.5 on 2025-10-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_business_district'),
        ('directory', '0019_auto_20251015_1131'),
    ]

    operations = [
    ]
