# Generated by Django 5.2.5 on 2025-10-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0016_remove_district_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
    ]
