# Generated by Django 5.2.5 on 2025-10-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_merge_0018_business_district_0019_auto_20251015_1131'),
        ('directory', '0021_auto_20251015_1142'),
    ]

    operations = [
    ]
