# Generated by Django 5.2.5 on 2025-10-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_update_payment_screenshot_storage'),  # Your latest migration
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.CharField(max_length=100, blank=True, null=True, default=''),
        ),
    ]
