# Generated by Django 5.2.5 on 2025-10-16 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_merge_20251015_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='business',
            name='district',
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='coupon_discount',
            field=models.IntegerField(default=20, help_text='Discount percentage for coupons (5-50%)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='business',
            name='coupon_enabled',
            field=models.BooleanField(default=True, help_text='Enable coupon requests for this business'),
        ),
        migrations.AddField(
            model_name='couponrequest',
            name='discount_percentage',
            field=models.IntegerField(default=20, help_text='Discount percentage (e.g., 20 for 20%)'),
        ),
        migrations.AddField(
            model_name='couponrequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='When the coupon was used', null=True),
        ),
        migrations.AddField(
            model_name='couponrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False, help_text='Coupon used by customer'),
        ),
        migrations.AddField(
            model_name='couponrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this coupon'),
        ),
        migrations.AlterField(
            model_name='couponrequest',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Email sent to customer'),
        ),
    ]
