# Generated by Django 5.2.5 on 2025-10-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_auto_20251015_1142'),  # Your latest migration
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;",
            reverse_sql="DROP EXTENSION IF EXISTS earthdistance CASCADE;"
        ),
    ]
